DROP database PRINNS; 
CREATE DATABASE PRINNS;

USE PRINNS;

CREATE TABLE SUCURSAL (

ID VARCHAR (4) UNIQUE PRIMARY KEY,

NOMBRE VARCHAR (50) NOT NULL,

CIUDAD VARCHAR (100)

);

-- Tabla EMPLEADO

CREATE TABLE EMPLEADO (

ID INT PRIMARY KEY AUTO_INCREMENT,

LEGAJO VARCHAR(1),

CUIL VARCHAR(20) NOT NULL,

APENOM VARCHAR(60) NOT NULL,

TELEFONO INT  NOT NULL

);

-- empleados de SUCURSALES

CREATE TABLE EMPLEADO_SUCURSAL (
ID INT   ,
LEGAJO INT  NOT NULL  PRIMARY KEY ,

IDSUCURSAL  VARCHAR (4)

);


-- Tabla FACTURACION 

CREATE TABLE FACTURACIONAB (

ID INT PRIMARY KEY AUTO_INCREMENT,

IDSUCURSAL VARCHAR(4),

FHVENTA DATE,

TIPOCOMPROBANTE VARCHAR (3),

CAJA INT (3) ,

LEGAJO INT NOT NULL,

NROCOMPROBANTE VARCHAR (20),

IMPORTE DECIMAL (14,4)

);

-- Tabla FACTURACION DETALLE

CREATE TABLE FACTURACIONDET (

IDFACTURA INT PRIMARY KEY,

DESCRIPCION VARCHAR (200),

IMPORTE DECIMAL (14,4)
);

-- tabla tipo comprobante

CREATE TABLE TIPOCOMPROBANTE (

ID VARCHAR (3) PRIMARY KEY,

NOMBRE VARCHAR (60),

ESTADO VARCHAR (1)

);

-- Tabla MEDIOS DE PAGO

CREATE TABLE MEDIODEPAGO (

IDMEDIODEPAGO INT PRIMARY KEY AUTO_INCREMENT,

IDSUCURSAL VARCHAR(4),

FHVENTA DATE,

TIPOCOMPROBANTE VARCHAR (3),

NROCOMPROBATE VARCHAR (50),

LEGAJO INT NOT NULL,

VARIEDAD INT,

IMPORTE decimal (14,4)

);



-- se crea una nueva tabla para poder validar el trigger auditoria_facturacioncab
CREATE TABLE auditoria_facturacionab (
    id_auditoria INT AUTO_INCREMENT PRIMARY KEY,
    id_factura INT NOT NULL,
    campo_modificado VARCHAR(50) NOT NULL,
    valor_anterior DECIMAL(14,4),
    valor_nuevo DECIMAL(14,4),
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario VARCHAR(50) NOT NULL
);
-- FACTURACION CABECERA

ALTER TABLE FACTURACIONAB
ADD CONSTRAINT FK_FACTURACIONDET_FACTURACIONAB
FOREIGN KEY (ID) REFERENCES FACTURACIONDET (IDFACTURA);

ALTER TABLE FACTURACIONAB
ADD CONSTRAINT FK_SUCURSAL_FACTURACIONAB
FOREIGN KEY (IDSUCURSAL) REFERENCES SUCURSAL(ID);


ALTER TABLE FACTURACIONAB
ADD CONSTRAINT FK__TIPOCOMPROBANTE_FACTURACIONAB
FOREIGN KEY (TIPOCOMPROBANTE) REFERENCES TIPOCOMPROBANTE (ID);

ALTER TABLE FACTURACIONAB
ADD CONSTRAINT FK__EMP_FACTURACIONCAB
FOREIGN KEY (LEGAJO) REFERENCES EMPLEADO_SUCURSAL (LEGAJO);


ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_SUCURSAL
FOREIGN KEY (ID) REFERENCES EMPLEADO_SUCURSAL (LEGAJO);

ALTER TABLE MEDIODEPAGO
ADD CONSTRAINT FK__EMP_MEDIODEPAGO
FOREIGN KEY (LEGAJO) REFERENCES EMPLEADO_SUCURSAL (LEGAJO);

ALTER TABLE MEDIODEPAGO
ADD CONSTRAINT FK__TIPOCOMPROBANTE_MEDIODEPAGO
FOREIGN KEY (TIPOCOMPROBANTE) REFERENCES TIPOCOMPROBANTE (ID);

ALTER TABLE MEDIODEPAGO
ADD CONSTRAINT FK_SUCURSAL_MEDIODEPAGO
FOREIGN KEY (IDSUCURSAL) REFERENCES SUCURSAL (ID);


