-- GENERAR EL DDL 
DROP DATABASE IF EXISTS NOAH_SISTEMAS ; -- reserv_ar
CREATE DATABASE NOAH_SISTEMAS;

USE NOAH_SISTEMAS;

-- Tabla PEDIDO
CREATE TABLE PEDIDO (
    IDPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT,
    IDPRODUCTO INT,
    IDEMPLEADO INT, 
    IDTIPOPEDIDO INT,
    FECHA DATETIME,
    CANCELACION DATETIME DEFAULT NULL
);

-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'USUARIO_UNKNOW',
    TELEFONO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(100) UNIQUE NOT NULL
);
-- EMPLEADO
CREATE TABLE EMPLEADO (
    IDEMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    TELEFONO VARCHAR(20),
    CORREO VARCHAR(100),
    IDEMPRESA INT
);

-- Tabla DUEÑO
CREATE TABLE DUEÑO (
    IDDUEÑO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    CORREO VARCHAR(100),
    TELEFONO VARCHAR(20)
);

-- Tabla TIPOPEDIDO
CREATE TABLE TIPOPEDIDO (
    IDTIPOPEDIDO INT AUTO_INCREMENT,
    TIPO VARCHAR(50),
    PRIMARY KEY (IDTIPOPEDIDO)
    );

-- Tabla EMPRESA
CREATE TABLE EMPRESA (
    IDEMPRESA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20)
);
-- Tabla MESA
CREATE TABLE PRODUCTO (
    IDPRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    IDEMPRESA INT,
    CAPACIDAD INT,
    DISPONIBLE BOOLEAN
);

-- FOREIGN KEYS DEFINITION

-- EMPLEADO
ALTER TABLE EMPLEADO
    ADD CONSTRAINT FK_EMP_CLIENTE
    FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA);
    
-- MESA
ALTER TABLE PRODUCTO
    ADD CONSTRAINT FK_PRODUCTO_EMPRESA
    FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA);
    
-- RESERVAS

ALTER TABLE PEDIDO
    ADD CONSTRAINT FK_PEDIDO_CLIENTE
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE PEDIDO
    ADD CONSTRAINT FK_PEDIDO_PRODUCTO
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);

ALTER TABLE PEDIDO
    ADD CONSTRAINT FK_PEDIDO_EMPLEADO
    FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);
    
ALTER TABLE PEDIDO
    ADD CONSTRAINT FK_PEDIDO_TIPOPEDIDO
    FOREIGN KEY (IDTIPOPEDIDO) REFERENCES TIPOPEDIDO(IDTIPOPEDIDO);




